### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by n1ck3** [ivanmaeder/vimv#3]
Hi,

I really like vimv, but had to hack it to work with py3. It works for me but I think might like py3 compatibility as well.

Cheers!

**Comment by ivanmaeder** [comment]
Hi Niclas,

Thanks! I don't work with Python so I had no idea.

I've installed Python 3.7.4 on my computer and fixed the errors. I've tested it and it works fine on my computer. Let me know how it goes for you.

Cheers,
Ivan

**Comment by n1ck3** [comment]
Super! The same changes I had made (except I hadn't bumped the version number) 🙂

Cheers!
