### ISSUE TITLE
Testing on windows

### ISSUE THREAD

**Issue by goyalyashpal** [ivanmaeder/vimv#5]
> `vimv` has NOT been tested on Windows.

### Summary:

- vimv.py works on Win 10
- Goto [#environment](#environment) for more details

### Steps:

```
bash
cd <address>
./vimv.py                                # relative address to pwd
```

or even just double clicking vimv.py to launch it

### Details:

- i did NOT move, rename, or `chmod` it (there was no `bin` under `usr/local`)
- I had to only change `vi` to `vim` or any other TUI text editor, as my system doesnt has vi

https://github.com/ivanmaeder/vimv/blob/661bafacc5065a70b62325909fdfa095d7b1a691/README.md?plain=1#L28-L32

> 2. Copy it to `/usr/local/bin/`
> 3. Rename it to `vimv`
> 4. Make it executable (`chmod +x /usr/local/bin/vimv`)

https://github.com/ivanmaeder/vimv/blob/661bafacc5065a70b62325909fdfa095d7b1a691/vimv.py#L43-L46

```
    else:
        editor = 'vi'
```

### Environment

- OS : Win 10 20H2
- Python 3.10.0
- Linux eviron : MSYS2
    - bash : 5.1.8
- VIM - Vi IMproved 8.2

**Comment by goyalyashpal** [comment]
it was working earlier, ain't anymore

**Comment by ivanmaeder** [comment]
Thanks @yashpalgoyal1304 

I don't really have an easy way to test on Windows, and I always assumed that users of the script would have the ability to get it to work.

But overall, I think the instructions are a bit out of date and I need to look into it.

**Comment by goyalyashpal** [comment]
it was working earlier, but not anymore. 

https://github.com/ivanmaeder/vimv/blob/661bafacc5065a70b62325909fdfa095d7b1a691/vimv.py#L33 

* and last time i checked the source, the methods used to read the CLI arguments i.e. the `optparse` is deprecated since v3.2 i.e. 2011.02.xx, more than a decade
* and currently python is on v3.11
* so, it ain't in a very good shape there...

i tried delving in the documentations to update that for doing a PR, but as i don't have much experience with python and how to test the changes, this would have been a new undertaking for me - which requires preaceful time - which i couldn't manage to gather.

> _Deprecated since version 3.2_: The [optparse](https://docs.python.org/3/library/optparse.html#module-optparse) module is deprecated and will not be developed further; development will continue with the [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) module.
>
> \- ref: _https://docs.python.org/3/library/optparse.html_

**Comment by ivanmaeder** [comment]
More than a decade… wow.

I will find some time to refresh this.

Thanks!
